config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('emailing.urls', namespace='emailing')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

emailing/urls.py
from django.urls import path

from emailing.apps import EmailingConfig
from emailing.views import EmailingListView, EmailingCreateView, EmailingUpdateView, EmailingDeleteView, \
    EmailingDetailView, ClientListView, ClientCreateView, ClientUpdateView, ClientDetailView, \
    ClientDeleteView, MessagesListView, MessagesCreateView, MessagesDetailView, MessagesUpdateView, MessagesDeleteView

app_name = EmailingConfig.name

urlpatterns = [
    path('', EmailingListView.as_view(), name='emailing_list'),
    path('emailing_create/', EmailingCreateView.as_view(), name='create_emailing'),
    path('emailing/<int:pk>/detail/', EmailingDetailView.as_view(), name='emailing_detail'),
    path('emailing/<int:pk>/update/', EmailingUpdateView.as_view(), name='emailing_update'),
    path('emailing/<int:pk>/delete/', EmailingDeleteView.as_view(), name='emailing_delete'),
    path('client/', ClientListView.as_view(), name='client_list'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/detail/', ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('message_list', MessagesListView.as_view(), name='message_list'),
    path('message_create/', MessagesCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/detail/', MessagesDetailView.as_view(), name='message_detail'),
    path('message/<int:pk>/update/', MessagesUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessagesDeleteView.as_view(), name='message_delete'),

]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
]

emailing/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Messages(models.Model):
    """Модель сообщения"""
    topic = models.CharField(max_length=50, verbose_name="тема письма", null=False, blank=False, unique=True)
    body = models.TextField(verbose_name="тело письма", null=False, blank=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name="Владелец")

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"


class Client(models.Model):
    """Модель клиента"""
    email = models.EmailField(unique=True, verbose_name='Почта')
    full_name = models.CharField(max_length=500, verbose_name='ФИО', **NULLABLE)
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    client_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                                     verbose_name='Владелец')

    def __str__(self):
        """Возвращает email клиента"""
        return f'{self.full_name} - {self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Emailing(models.Model):
    """Модель рассылки"""
    PERIOD_DAILY = "Ежедневно"
    PERIOD_WEEKLY = "weekly"
    PERIOD_MONTHLY = "monthly"

    PERIODS = (
        ("PERIOD_DAILY", "ежедневно"),
        ("PERIOD_WEEKLY", "еженедельно"),
        ("PERIOD_MONTHLY", "ежемесячно"),
    )

    STATUS_CREATED = "created"
    STATUS_STARTED = "started"
    STATUS_DONE = "done"

    STATUSES = (
        ('STATUS_DONE', 'завершена'),
        ('STATUS_CREATED', 'создана'),
        ('STATUS_STARTED', 'запущена'),
    )

    title = models.CharField(max_length=100, verbose_name='название рассылки', unique=True, **NULLABLE)
    start_time = models.DateTimeField(verbose_name="Время начала")
    end_time = models.DateTimeField(verbose_name="Время завершения", **NULLABLE)
    send_periodicity = models.CharField(choices=PERIODS, default=PERIOD_DAILY, verbose_name='периодичность')
    emailing_status = models.CharField(choices=STATUSES, default=STATUS_CREATED, verbose_name='статус')
    emailing_clients = models.ManyToManyField(Client, related_name="mailing_settings", verbose_name='клиенты')
    message = models.ForeignKey(Messages, on_delete=models.SET_NULL, **NULLABLE)
    emailing_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец',
                                       null=True)
    is_active = models.BooleanField(default=True, verbose_name="статус активности")

    def __str__(self):
        return f'Рассылка {self.title} в {self.start_time} ({self.send_periodicity})'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        permissions = [
            ("switch_status", "изменение статуса"),
            ("view_mailing", "отображать рассылки")
        ]


class EmailingLog(models.Model):
    """Модель статистики рассылок"""
    STATUS_OK = "ok"
    STATUS_FAILED = "failed"

    STATUS_ATTEMPT = (
        ('STATUS_OK', 'УСПЕШНО'),
        ('STATUS_FAILED', 'НЕ УСПЕШНО'),
    )

    last_try = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата последней попытки", **NULLABLE
    )
    client = models.ForeignKey(
        Client, on_delete=models.SET_NULL, verbose_name="Клиент", **NULLABLE
    )
    settings = models.ForeignKey(
        Emailing, on_delete=models.SET_NULL, verbose_name="Настройки", **NULLABLE
    )

    log_status = models.CharField(max_length=20, choices=STATUS_ATTEMPT, default=STATUS_OK,
                                  verbose_name='статус попытки')
    response = models.CharField(max_length=350, **NULLABLE, verbose_name='ответ сервера')

    class Meta:
        verbose_name = 'попытка рассылки'
        verbose_name_plural = 'попытки рассылки'

emailing/forms.py
from django import forms

from emailing.models import Client, Emailing, Messages


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_published':
                field.widget.attrs['class'] = 'form-control'


class MessagesForm(StyleFormMixin, forms.ModelForm):
    """Форма сообщения"""

    class Meta:
        model = Messages
        fields = ["topic", "body", "owner"]


class EmailingForm(StyleFormMixin, forms.ModelForm):
    """Форма рассылки"""

    class Meta:
        model = Emailing
        exclude = ('emailing_owner',)


class ClientForm(StyleFormMixin, forms.ModelForm):
    """Форма клиента"""

    class Meta:
        model = Client
        fields = ["full_name", "email", "description"]

emailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from emailing.forms import EmailingForm, ClientForm, MessagesForm
from emailing.models import Emailing, Client, Messages, EmailingLog


class MessagesListView(ListView):
    model = Messages
    extra_context = {
        'title': 'Сообщения'
    }

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name='manager').exists() or user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                owner=user.pk
            )
        return queryset


class MessagesCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """Создание сообщения"""
    model = Messages
    form_class = MessagesForm
    extra_context = {
        'title': 'Добавление сообщения'
    }

    def test_func(self):
        user = self.request.user
        if not user.groups.filter(name='manager').exists() and not user.groups.filter(name='content_manager').exists():
            return True
        return False

    def get_success_url(self):
        return reverse('emailing:message_detail', args=[self.object.pk])

    def form_valid(self, form):
        user = self.request.user
        self.object = form.save()
        self.object.emailing_owner = user
        self.object.save()
        return redirect(self.get_success_url())

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:message_list'))


class MessagesUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Редактирование рассылки"""
    model = Messages
    form_class = MessagesForm
    extra_context = {
        'title': 'Редактирование сообщения'
    }

    def test_func(self):
        user = self.request.user
        message = self.get_object()

        if message.owner == user or user.groups.filter(name='manager').exists() or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:message_list'))

    def get_success_url(self):
        return reverse('emailing:message_detail', args=[self.object.pk])


class MessagesDetailView(DetailView, UserPassesTestMixin):
    """Детали сообщения"""
    model = Messages
    extra_context = {
        'title': 'Детали сообщения'
    }

    def test_func(self):
        user = self.request.user
        message = self.get_object()

        if message.owner == user or user.groups.filter(name='manager').exists() or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:message_list'))


class MessagesDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Удаление сообщения"""
    model = Messages
    success_url = reverse_lazy('emailing:message_list')
    extra_context = {
        'title': 'Удаление рассылки'
    }

    def test_func(self):
        user = self.request.user
        message = self.get_object()

        if message.owner == user or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:message_list'))


class EmailingListView(ListView):
    model = Emailing
    extra_context = {
        'title': 'Рассылки'
    }

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name='manager').exists() or user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                emailing_owner=user.pk
            )
        return queryset


class EmailingCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """Создание рассылки"""
    model = Emailing
    form_class = EmailingForm
    extra_context = {
        'title': 'Добавление рассылки'
    }

    def test_func(self):
        user = self.request.user
        if not user.groups.filter(name='manager').exists() and not user.groups.filter(name='content_manager').exists():
            return True
        return False

    def get_success_url(self):
        return reverse('emailing:emailing_detail', args=[self.object.pk])

    def form_valid(self, form):
        user = self.request.user
        self.object = form.save()
        self.object.emailing_owner = user
        self.object.save()
        return redirect(self.get_success_url())

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:emailing_list'))


class EmailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Редактирование рассылки"""
    model = Emailing
    form_class = EmailingForm
    extra_context = {
        'title': 'Редактирование рассылки'
    }

    def test_func(self):
        user = self.request.user
        emailing = self.get_object()

        if emailing.emailing_owner == user or user.groups.filter(name='manager').exists() or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:emailing_list'))

    def get_success_url(self):
        return reverse('emailing:emailing_detail', args=[self.object.pk])


class EmailingDetailView(DetailView, UserPassesTestMixin):
    """Детали рассылки"""
    model = Emailing
    extra_context = {
        'title': 'Детали рассылки'
    }

    def test_func(self):
        user = self.request.user
        emailing = self.get_object()

        if emailing.emailing_owner == user or user.groups.filter(name='manager').exists() or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:emailing_list'))


class EmailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Удаление рассылки"""
    model = Emailing
    success_url = reverse_lazy('emailing:emailing_list')
    extra_context = {
        'title': 'Удаление рассылки'
    }

    def test_func(self):
        user = self.request.user
        emailing = self.get_object()

        if emailing.emailing_owner == user or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:emailing_list'))


class ClientListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Client
    extra_context = {
        'title': 'Мои клиенты'
    }

    def test_func(self):
        user = self.request.user
        if not user.is_staff or user.is_superuser:
            return True
        return False

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                client_owner=user.pk
            )
        return queryset

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:emailing_list'))


class ClientCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """Создание клиента"""
    model = Client
    form_class = ClientForm
    extra_context = {
        'title': 'Добавление клиента'
    }

    def test_func(self):
        user = self.request.user
        if not user.is_staff or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:emailing_list'))

    def get_success_url(self):
        return reverse('emailing:client_detail', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.client_owner = self.request.user
        self.object.save()
        return redirect(self.get_success_url())


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Редактирование клиента"""
    model = Client
    form_class = ClientForm
    extra_context = {
        'title': 'Редактирование клиента'
    }

    def test_func(self):
        user = self.request.user
        mailing = self.get_object()

        if mailing.client_owner == user or user.is_staff:
            return True
        return False

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.client_owner != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:client_list'))

    def get_success_url(self):
        return reverse('emailing:client_detail', args=[self.object.pk])


class ClientDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """Детали клиента"""
    model = Client
    extra_context = {
        'title': 'Информация о клиенте'
    }

    def test_func(self):
        user = self.request.user
        if not user.is_staff or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:emailing_list'))


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Удаление клиента"""
    model = Client
    success_url = reverse_lazy('emailing:client_list')
    extra_context = {
        'title': 'Удаление клиента'
    }

    def test_func(self):
        user = self.request.user
        if not user.is_staff or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('emailing:emailing_list'))


class EmailingLogListView(LoginRequiredMixin, ListView):
    model = EmailingLog

emailing/templates/emailing/client_confirm_delete.html
{% extends 'emailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <div class="card text-center">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента '{{object.full_name}}'?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'emailing:client_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

emailing/templates/emailing/client_detail.html
{% extends 'emailing/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row justify-content-md-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Информация о клиенте
                        </h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <tbody>
                            <tr>
                                <th scope="row">Электронная почта</th>
                                <td>{{ object.email }}</td>
                            </tr>
                            <tr>
                                <th scope="row">ФИО</th>
                                <td>{{ object.full_name }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Комментарий</th>
                                <td>{{ object.description }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Владелец</th>
                                <td>{{ object.client_owner }}</td>
                            </tr>
                            </tbody>
                        </table>

                        <div class="text-center">
                            <a href="{% url 'emailing:client_update' object.pk %}" class="btn btn-primary">Изменить</a>
                            <a href="{% url 'emailing:client_delete' object.pk %}" class="btn btn-danger">Удалить</a>
                        </div>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

emailing/templates/emailing/client_form.html
{% extends 'emailing/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-md-center">

        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

emailing/templates/emailing/client_list.html
{% extends 'emailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Клиенты</h1>

    </div>
</section>

<div class="container">
    <div class="row">
        <div class="col-12 mb-5">
            <a type="button" class="btn btn-sm btn-outline-danger" href="{% url 'emailing:client_create' %}">Добавить
                клиента</a>
        </div>
    </div>
</div>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.email }}</h5>
                        <p class="card-text">ФИО: {{ object.full_name }}</p>
                        <p class="card-text">Владелец: {{ object.client_owner }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'emailing:client_detail' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Подробнее</a>
                            <small class="text-muted">{{ object.description }}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

emailing/templates/emailing/emailing_confirm_delete.html
{% extends 'emailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <div class="card text-center">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку '{{object.title}}'?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'emailing:emailing_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

emailing/templates/emailing/emailing_detail.html
{% extends 'emailing/base.html' %}

{% block content %}
<table class="table table-striped">
    <thead>
    <tr>
        <th>Тема рассылки</th>
        <th>Сообщение</th>
        <th>Время рассылки</th>
        <th>Периодичность</th>
        <th>Статус</th>
        <th>Подписчики</th>
        <th>Владелец</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ object.subject }}</td>
        <td>{{ object.body }}</td>
        <td>{{ object.time_to_send }}</td>
        <td>{{ object.send_periodicity }}</td>
        <td>{{ object.emailing_status }}</td>
        <td>
            <ul>
                {% for client in emailing.emailing_clients.all %}
                <li>{{ client.email }}</li>
                {% endfor %}
            </ul>
        </td>
        <td>{{ object.emailing_owner }}</td>
    </tr>
    </tbody>
</table>

<div class="text-center">
    <a href="{% url 'emailing:emailing_update' object.pk %}" class="btn btn-primary">Редактировать</a>
    <a href="{% url 'emailing:emailing_delete' object.pk %}" class="btn btn-danger">Удалить</a>
</div>
{% endblock %}

emailing/templates/emailing/emailing_list.html
{% extends 'emailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Управление рассылками</h1>

    </div>
</section>

<div class="container">
    <div class="row">
        <div class="col-12 mb-5">
            <a type="button" class="btn btn-sm btn-outline-danger" href="{% url 'emailing:create_emailing' %}">Создать
                рассылку</a>
        </div>
    </div>
</div>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.subject }}</h5>
                        <p class="card-text">{{ object.send_periodicity }}</p>
                        <p class="card-text">{{ object.time_to_send }}</p>
                        <p class="card-text">Владелец {{ object.emailing_owner }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'emailing:emailing_detail' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Подробнее</a>
                            <small class="text-muted">{{ object.emailing_status }}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

emailing/templates/emailing/emailing_logs.html
{% extends 'emailing/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Логи рассылки "{{ emailing.subject }}"</h1>

    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Дата и время</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Подписчик</th>
                    <th scope="col">Ответ сервера</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs %}
                <tr>
                    <td>{{ log.created_time }}</td>
                    <td>
                        {% if log.log_status == 'ok' %}
                        <span class="badge badge-success">Успешно</span>
                        {% else %}
                        <span class="badge badge-danger">Ошибка</span>
                        {% endif %}
                    </td>
                    <td>{{ log.log_client }}</td>
                    <td>{{ log.response }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Нет доступных логов для этой рассылки.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{% url 'emailing:emailing_detail' emailing.pk %}" class="btn btn-secondary">Назад</a>
</div>
{% endblock %}

emailing/templates/emailing/messages_confirm_delete.html
{% extends 'emailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <div class="card text-center">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить сообщение?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'emailing:client_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

emailing/templates/emailing/messages_detail.html
{% extends 'emailing/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row justify-content-md-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Детали сообщения
                        </h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <tbody>
                            <tr>
                                <th scope="row">Тема</th>
                                <td>{{ object.topic }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Текст сообщения</th>
                                <td>{{ object.body }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Владелец</th>
                                <td>{{ object.owner }}</td>
                            </tr>
                            </tbody>
                        </table>

                        <div class="text-center">
                            <a href="{% url 'emailing:message_update' object.pk %}" class="btn btn-primary">Изменить</a>
                            <a href="{% url 'emailing:message_delete' object.pk %}" class="btn btn-danger">Удалить</a>
                        </div>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

emailing/templates/emailing/messages_list.html
{% extends 'emailing/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Управление сообщениями</h1>

    </div>
</section>

<div class="container">
    <div class="row">
        <div class="col-12 mb-5">
            <a type="button" class="btn btn-sm btn-outline-danger" href="{% url 'emailing:message_create' %}">Создать
                новое сообщение</a>
        </div>
    </div>
</div>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.topic }}</h5>
                        <p class="card-text">Владелец {{ object.owner }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'emailing:message_detail' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Подробнее</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}